spring:
#  init:
#    mode: always
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://database-1.c62snh2lrenz.ap-northeast-2.rds.amazonaws.com:3306/studyshare
    username: admin
    password: tkdrud11
    driver-class-name: org.mariadb.jdbc.Driver

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging:
  level:
    twentyOnes.studyshare: DEBUG

spring.jpa.defer-datasource-initialization: true